// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl2bgI_PxRFbWIe-dSRpPFEQY_JMNv8qE',
    appId: '1:643472782731:web:92f4632fca669bd6de6b8e',
    messagingSenderId: '643472782731',
    projectId: 'admin-pribumiapp',
    authDomain: 'admin-pribumiapp.firebaseapp.com',
    storageBucket: 'admin-pribumiapp.appspot.com',
    measurementId: 'G-TXHTLWPHT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCCeMUyZX1hDSowNtBHRhoTzZK114PkE',
    appId: '1:643472782731:android:be635e6759f9dc29de6b8e',
    messagingSenderId: '643472782731',
    projectId: 'admin-pribumiapp',
    storageBucket: 'admin-pribumiapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPElZa631Ia9PfFh5UsQjGu7Yd6_qLI0',
    appId: '1:643472782731:ios:b54b0ec17200b688de6b8e',
    messagingSenderId: '643472782731',
    projectId: 'admin-pribumiapp',
    storageBucket: 'admin-pribumiapp.appspot.com',
    iosBundleId: 'com.example.adminApps',
  );
}
